using System.Text;
using System.Xml.Linq;

namespace Ahjo.Vulkan.ResultPolicyGen;

// Reads vk.xml and emits a committed table of every Vulkan command whose
// `successcodes` set carries more than one code — i.e. every entry point for
// which a plain "== VK_SUCCESS" check (the wrapper's `ThrowIfFailed`) is the
// wrong success predicate.
//
// This is the data half of issue #117: the #97 bug class (throwing on
// VK_INCOMPLETE across enumerate / get-data / surface-query sites) happened
// because nothing machine-checked which entry points have multi-code success
// sets. The emitted table is consumed by a guard unit test
// (ResultPolicyGuardTests) that scans the wrapper sources for
// `vk<Command>(...).ThrowIfFailed()` and fails on any multi-success command,
// so the contract is derived from the spec registry instead of resting on a
// doc-comment convention.
//
// Output (one file): a `ResultPolicyData` class mapping command name → its
// full success-code set, ordered by command name for a stable diff.
//
// Aliases (`<command name="X" alias="Y"/>`) are resolved to their target's
// success set, so calling the alias name is caught the same as the canonical
// name. This mirrors StructExtendsGen's vk.xml reading pattern — an extension
// of an existing codegen path, not new machinery.
internal static class Program
{
    private static int Main(string[] args)
    {
        if (args.Length != 2)
        {
            Console.Error.WriteLine("Usage: Ahjo.Vulkan.ResultPolicyGen <vk.xml> <output-file>");
            return 2;
        }

        var vkXmlPath = args[0];
        var outputPath = args[1];

        var (canonical, aliases) = ReadCommands(vkXmlPath);

        // command name -> success-code set, including resolved aliases.
        var multiSuccess = new SortedDictionary<string, string[]>(StringComparer.Ordinal);
        foreach (var (name, codes) in canonical)
        {
            if (codes.Length > 1)
            {
                multiSuccess[name] = codes;
            }
        }

        foreach (var (aliasName, target) in aliases)
        {
            // Resolve transitively: vk.xml can in principle chain aliases
            // (A -> B -> C) where only C is the canonical command. Today's
            // pinned headers have no chained aliases, but a future bump might,
            // and a single-level lookup would silently drop the entry.
            var current = target;
            while (!canonical.ContainsKey(current) && aliases.TryGetValue(current, out var next))
            {
                current = next;
            }

            if (canonical.TryGetValue(current, out var codes) && codes.Length > 1)
            {
                multiSuccess[aliasName] = codes;
            }
        }

        Console.WriteLine($"vk.xml declares {canonical.Count} commands ({aliases.Count} aliases); {multiSuccess.Count} are multi-success (incl. aliases).");

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, Emit(multiSuccess));
        Console.WriteLine($"Wrote {outputPath}.");
        return 0;
    }

    private static (Dictionary<string, string[]> canonical, Dictionary<string, string> aliases) ReadCommands(string path)
    {
        var doc = XDocument.Load(path);
        var canonical = new Dictionary<string, string[]>(StringComparer.Ordinal);
        var aliases = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var command in doc.Descendants("command"))
        {
            // Alias form: <command name="vkFooKHR" alias="vkFoo"/> — no proto.
            var aliasTarget = (string?)command.Attribute("alias");
            if (aliasTarget is not null)
            {
                var aliasName = (string?)command.Attribute("name");
                if (!string.IsNullOrEmpty(aliasName))
                {
                    aliases[aliasName] = aliasTarget;
                }
                continue;
            }

            var name = command.Element("proto")?.Element("name")?.Value;
            if (string.IsNullOrEmpty(name)) continue;

            var successcodes = (string?)command.Attribute("successcodes");
            var codes = string.IsNullOrEmpty(successcodes)
                ? []
                : successcodes.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            canonical[name] = codes;
        }

        return (canonical, aliases);
    }

    private static string Emit(SortedDictionary<string, string[]> multiSuccess)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Source: vk.xml command successcodes (commands whose contract carries more");
        sb.AppendLine("// than one success code). Regenerate with:");
        sb.AppendLine("//   dotnet build src/Ahjo.Vulkan.Native -t:RegenerateResultPolicy");
        sb.AppendLine("// Edits to this file are overwritten.");
        sb.AppendLine("namespace Ahjo.Vulkan.Tests.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class ResultPolicyData");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Vulkan commands whose <c>successcodes</c> set in vk.xml carries more than");
        sb.AppendLine("    /// one code — i.e. a plain <c>== VK_SUCCESS</c> check (<c>ThrowIfFailed</c>)");
        sb.AppendLine("    /// is the wrong success predicate. Maps command name to its full");
        sb.AppendLine("    /// success-code set, including resolved aliases.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static readonly System.Collections.Generic.IReadOnlyDictionary<string, string[]> MultiSuccessCommands =");
        sb.AppendLine("        new System.Collections.Generic.Dictionary<string, string[]>(System.StringComparer.Ordinal)");
        sb.AppendLine("        {");
        foreach (var (name, codes) in multiSuccess)
        {
            sb.Append("            [\"").Append(name).Append("\"] = [");
            for (var i = 0; i < codes.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append('"').Append(codes[i]).Append('"');
            }
            sb.AppendLine("],");
        }
        sb.AppendLine("        };");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
